# 博客名称
_name: TeanBlog
# SEO desc、首页二级标题
_desc: 基于 Egg.js 的简约博客

# 首页
_home:
  # 项目展示
  projects:
    enable: false
    content:
      - name: TeanBlog
        url: https://github.com/TeanBlog/TeanBlog

# 博客页
_blog:
  # 二级标题
  desc:

# 友链页面
_link:
  enable: false
  # 二级标题
  desc:
  content:
    - name: Trevor
      url: https://trevor.top

# 关于页面
_about:
  enable: false
  nickname: Trevor
  # 关于页面二级标题
  desc: 万里不惜死，朝得成功
  introduction: 个人简介
  # 技能
  skill:
    content:
      - name: JavaScript
  # 联系方式
  contact:
    content:
      - name: GitHub
        url: https://github.com/HuangXiZhou
      - name: Email
        url: mailto:xizhouh@gmail.com # 必须是 mailto: 开头

# 评论模块
_gitalk:
  enable: false
  clientId: GitHub client ID
  clientSecret: GitHub client secret
  repo: 仓库名
  owner: 拥有人
  admin: 拥有人 # 目前只支持一个管理员

# json feed (https://jsonfeed.org/2017/05/17/announcing_json_feed)
_feed:
  title: 标题
  description: 描述
  link: 站点主页
  author:
    name: 名称

_system:
  key: 秘钥 # 不能设置数字 必须为 String 字符串
  jwt: 秘钥 # 不能设置数字 必须为 String 字符串
  db:
    username: 数据库账号
    password: 数据库密码 # 不能设置数字 必须为 String 字符串
